
---
-name: Criar usuário com sudo
 user:
   name: "{{ item.name }}"
   comment: "{{ item.comment }}"
   password: "{{ item.password password_hash('sha512') }}"
   shell: /bin/bash
   groups: sudo
   state: present
  loop:
    - { name: "devops", comment: "DevOps User", password: "senhahash" }
